### ISSUE TITLE
Track the deno version used to generate the lockfile in the lockfile

### ISSUE THREAD

**Issue by zebreus** [denoland/deno_lockfile#29]
Deno currently fetches the dependencies using a user agent with the current Deno version (like `User-Agent: Deno/1.44.4`). Some servers (e.g. esm.sh) serve different files depending on the user agent as shown in the example below. The Deno version is not tracked in the lockfile, we can get different dependencies when using a different version of Deno, even though the lockfile did not change.

## Motivation

I want to be able to create reproducible/deterministic vendored dependencies from a deno lockfile.

## Examples

Some package registries treat us differently depending on the headers we send. 

```console
$ curl https://esm.sh/preact@10.22.1/jsx-runtime
/* esm.sh - preact@10.22.1/jsx-runtime */
import "/stable/preact@10.22.1/esnext/preact.mjs";
export * from "/stable/preact@10.22.1/esnext/jsx-runtime.js";
```

If we set our user agent to `Deno/1.44.4`, we get a different file:

```console
$ curl -H 'User-Agent: Deno/1.44.4' https://esm.sh/preact@10.22.1/jsx-runtime
/* esm.sh - preact@10.22.1/jsx-runtime */
import "/stable/preact@10.22.1/denonext/preact.mjs";
export * from "/stable/preact@10.22.1/denonext/jsx-runtime.js";
```

If we set our user agent to `Deno/1.13.0`, we again get a different result with `deno` instead of `denonext`:

```console
$ curl -H 'User-Agent: Deno/1.13.0' https://esm.sh/preact@10.22.1/jsx-runtime
/* esm.sh - preact@10.22.1/jsx-runtime */
import "/stable/preact@10.22.1/deno/preact.mjs";
export * from "/stable/preact@10.22.1/deno/jsx-runtime.js";

```

**Comment by dsherret** [comment]
I think this is too much information to track beyond the checksum.

> I want to be able to create reproducible/deterministic vendored dependencies from a deno lockfile.

I think that `"vendor": true` is the only way to do this? esm.sh is constantly updating so even providing a consistent user agent won't help.

**Comment by zebreus** [comment]
Yes, for now I am using "vendor": true to build the vendored dependencies (`deno cache --lock --vendor --node-modules-dir` to be exact). In the future I would love to be able to have a command in deno to fetch and verify dependencies using only the lockfile and not the code.

I was under the impression, that esm.sh will always serve the same file, when the same URL is used, an exact version is requested, and the same headers are send. But I could be mistaken here.

We could track just one denoVersion field for the entire lockfile, to keep the lockfile uncluttered.
