### ISSUE TITLE
Add received HTTP headers to the lockfile

### ISSUE THREAD

**Issue by zebreus** [denoland/deno_lockfile#32]
When vendoring dependencies with `"vendor": true` some received HTTP headers are stored in the `manifest.json` in the `vendor` folder, but they are not tracked in the lockfile. When recreating vendored dependencies, we can not verify whether the servers responded with the same headers, or different ones. This is an issue when building Deno applications with nix (a reproducible, hash-addressed build system that forbids unrestricted network access at build time).

This could be fixed by adding a section containing the relevant received headers to the bottom of the lockfile.

**Comment by dsherret** [comment]
Similar to https://github.com/denoland/deno_lockfile/issues/29#issuecomment-2254178396 I think this is too much information to store in the lockfile. 

> When recreating vendored dependencies

I think the `vendor` folder should be checked into source control as it contains the headers.

**Comment by dsherret** [comment]
Also going to close because the vendor folder should be used for this.
